server:
  port: 8080

spring:
  application:
    name: taxi-dispatcher
  datasource:
    url: jdbc:h2:mem:taxi;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop   # 개발/테스트: 시작 시 생성, 종료 시 제거
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: false
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace  # Hibernate 6 바인드 파라미터 로깅
    org.springframework.data.repository.config: debug